import {
    MdDashboard,
    MdShoppingCart,
    MdAddCircleOutline,
    MdPerson,
    MdMonetizationOn,
    MdSettings,
    MdArchive,
    MdQuestionAnswer,
    MdCategory,
    MdCached,
    MdCreditCard,
} from 'react-icons/md';

export const allNav = [
    {
        id: 1,
        title: 'Dashboard',
        icon: <MdDashboard />,
        role: 'admin',
        path: '/admin/dashboard',
    },
    {
        id: 2,
        title: 'Orders',
        icon: <MdShoppingCart />,
        role: 'admin',
        path: '/admin/dashboard/orders',
    },
    {
        id: 3,
        title: 'Category',
        icon: <MdCategory />,
        role: 'admin',
        path: '/admin/dashboard/category',
    },
    {
        id: 4,
        title: 'Sellers',
        icon: <MdPerson />,
        role: 'admin',
        path: '/admin/dashboard/sellers',
    },
    {
        id: 5,
        title: 'Payment request',
        icon: <MdMonetizationOn />,
        role: 'admin',
        path: '/admin/dashboard/payment-request',
    },
    {
        id: 6,
        title: 'Deactive Sellers',
        icon: <MdSettings />,
        role: 'admin',
        path: '/admin/dashboard/deactive-sellers',
    },
    {
        id: 7,
        title: 'Sellers Request',
        icon: <MdCached />,
        role: 'admin',
        path: '/admin/dashboard/sellers-request',
    },
    {
        id: 9,
        title: 'Dashboard',
        icon: <MdDashboard />,
        role: 'seller',
        path: '/seller/dashboard',
    },
    {
        id: 10,
        title: 'Add Product',
        icon: <MdAddCircleOutline />,
        role: 'seller',
        path: '/seller/dashboard/add-product',
    },
    {
        id: 11,
        title: 'All Product',
        icon: <MdArchive />,
        role: 'seller',
        path: '/seller/dashboard/products',
    },
    {
        id: 12,
        title: 'Discount Product',
        icon: <MdArchive />,
        role: 'seller',
        path: '/seller/dashboard/discount-products',
    },
    {
        id: 13,
        title: 'Orders',
        icon: <MdShoppingCart />,
        role: 'seller',
        path: '/seller/dashboard/orders',
    },
    {
        id: 14,
        title: 'Payments',
        icon: <MdCreditCard />,
        role: 'seller',
        path: '/seller/dashboard/payments',
    },
    {
        id: 17,
        title: 'Profile',
        icon: <MdPerson />,
        role: 'seller',
        path: '/seller/dashboard/profile',
    },
];
